Fix build: /usr/bin/ld: CMakeFiles/obexftpd_app.dir/obexftpd.c.o: undefined reference to symbol 'OBEX_Cleanup' /usr/lib/x86_64-linux-gnu/libopenobex.so.2: error adding symbols: DSO missing from command line